name: Build WslManager App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore the application
        run: msbuild WslManager.sln /m /t:Restore /p:Configuration=${{ matrix.configuration }}

      - name: Create the app package
        run: msbuild WslManager.Package\WslManager.Package.wapproj /m /t:Publish /p:Configuration=${{ matrix.configuration }} /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }} /p:Platform=x64 /p:AppxBundlePlatforms=x64

      - name: Compress archive
        run: Compress-Archive -Path "WslManager.Package/AppPackages" -DestinationPath "WslManager.Package/AppPackages_${{ matrix.configuration }}.zip" -CompressionLevel Optimal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MSIX Bundle Package
          path: "WslManager.Package/AppPackages_${{ matrix.configuration }}.zip"
