name: Build and Publish WslManager App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check if Chocolatey is installed
        run: choco --version
        continue-on-error: true
        id: check_choco

      - name: Install Chocolatey
        if: steps.check_choco.outcome != 'success'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Check if MSBuild is installed
        run: msbuild /version
        continue-on-error: true
        id: check_msbuild

      - name: Install MSBuild
        if: steps.check_msbuild.outcome != 'success'
        run: |
          choco install -y visualstudio2019buildtools --version=16.11.7.0
          refreshenv

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore the application
        run: msbuild WslManager.sln /m /t:Restore /p:Configuration=Release

      - name: Create the app package
        run: msbuild WslManager.Package\WslManager.Package.wapproj /m /t:Publish /p:Configuration=Release /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }} /p:Platform=x64 /p:AppxBundlePlatforms=x64

      - name: Compress archive
        run: Compress-Archive -Path "WslManager.Package/AppPackages" -DestinationPath "WslManager.Package/AppPackages_Release.zip" -CompressionLevel Optimal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MSIX Bundle Package
          path: "WslManager.Package/AppPackages_Release.zip"
